Feature: Product Category
  As a demo.nopcommerce.com user
  I want to see product category list on home page
  Background:
    Scenario: To verify
      Given user is on home page of demo.nopcommerce.com
      When click on computer category page
      Then user should see desktop, notebook and software subcategory



      Feature : Product Category As a demo.nopcommerce.com user
        I want to see product category list on home page
        Background:
        Scenario: To verify
          Given user is on home page of demo.nopcommerce.com
          When click on  Electronic category page
          Then user should see Camera &Photos, cellphone and others as  subcategory


        As a demo.nopcommerce.com user
        I want to see product category list on home page

        Scenario: To verify
          Given user is on home page of demo.nopcommerce.com
          When click on apparel category page
          Then user should see Shoes, Clothing and Accessories as subcategory


        As a demo.nopcommerce.com user
        I want to see product category list on home page

        Scenario: To verify
          Given user is on home page of demo.nopcommerce.com
          When click on Digital downloads category page
          Then user should see If You Wait,NightVision,Science & Faith as  subcategory



        As a demo.nopcommerce.com user
        I want to see product category list on home page

        Scenario: To verify
          Given user is on home page of demo.nopcommerce.com
          When click on Book category page
          Then user should see Fahrenheit 451 by Ray Bradbury ,First Prize Pies,Pride and Prejudice as subcategory


        As a demo.nopcommerce.com user
        I want to see product category list on home page

        Scenario: To verify
          Given user is on home page of demo.nopcommerce.com
          When click on Jewelry category page
          Then user should see Elegant Gemstone Necklace (rental), Flower Girl Bracelet,Vintage Style Engagement Ring as subcategory



        As a demo.nopcommerce.com user
        I want to see product category list on home page

        Scenario: To verify
          Given user is on home page of demo.nopcommerce.com
          When click on Gift Card category page
          Then user should see $25 Virtual Gift Card,$50 Physical Gift Card ,$100 Physical Gift Card as subcategory



